ExternalDomain: localhost
ExternalSecure: false
TLS:
  Enabled: false

Database:
  postgres:
    Host: db
    Port: 5432
    Database: zitadel
    User:
      Username: zitadel
      Password: zitadel
      SSL:
        Mode: disable
    Admin:
      Username: postgres
      Password: postgres
      SSL:
        Mode: disable

DefaultInstance:
  Features:
    LoginV2:
      Required: true
      BaseURI: http://localhost:9090/ui/v2/login

OIDC:
  DefaultLoginURLV2: http://localhost:9090/ui/v2/login/login?authRequest=
  DefaultLogoutURLV2: http://localhost:9090/ui/v2/login/logout?post_logout_redirect=
SAML:
  DefaultLoginURLV2: http://localhost:9090/ui/v2/login/login?samlRequest=
